# Stock Sentiment Analysis using News Headlines

# Importing Dataset

import pandas as pd

In [12]:
df = pd.read_csv("C:/Users/atharva/OneDrive/Desktop/self learn data science/machine learning algorithms/Text Analytics/Sentiment analysis/stock sentiment analysisi/Data.csv", encoding = 'ISO-8859-1')

In [13]:
df.head()

Date  Label                                               Top1  \
0  2000-01-03      0  A 'hindrance to operations': extracts from the...   
1  2000-01-04      0                                          Scorecard   
2  2000-01-05      0                  Coventry caught on counter by Flo   
3  2000-01-06      1                      Pilgrim knows how to progress   
4  2000-01-07      1                               Hitches and Horlocks   

                                 Top2  \
0                           Scorecard   
1                 The best lake scene   
2  United's rivals on the road to Rio   
3                 Thatcher facing ban   
4      Beckham off but United survive   

                                            Top3  \
0                Hughes' instant hit buoys Blues   
1                  Leader: German sleaze inquiry   
2  Thatcher issues defence before trial by video   
3        McIlroy calls for Irish fighting spirit   
4                        Breast cancer screening   

                                            Top4  \
0       Jack gets his skates on at ice-cold Alex   
1                                  Cheerio, boyo   
2  Police help Smith lay down the law at Everton   
3                Leicester bin stadium blueprint   
4                                    Alan Parker   

                                          Top5  \
0       Chaos as Maracana builds up for United   
1                     The main recommendations   
2  Tale of Trautmann bears two more retellings   
3               United braced for Mexican wave   
4      Guardian readers: are you all whingers?   

                                                Top6  \
0  Depleted Leicester prevail as Elliott spoils E...   
1                             Has Cubie killed fees?   
2                                England on the rack   
3  Auntie back in fashion, even if the dress look...   
4                                   Hollywood Beyond   

                                              Top7  \
0                 Hungry Spurs sense rich pickings   
1                           Has Cubie killed fees?   
2  Pakistan retaliate with call for video of Walsh   
3                    Shoaib appeal goes to the top   
4                               Ashes and diamonds   

                                                Top8  ...  \
0                  Gunners so wide of an easy target  ...   
1                             Has Cubie killed fees?  ...   
2               Cullinan continues his Cape monopoly  ...   
3  Hussain hurt by 'shambles' but lays blame on e...  ...   
4                   Whingers - a formidable minority  ...   

                                               Top16  \
0           Flintoff injury piles on woe for England   
1                               On the critical list   
2                        South Melbourne (Australia)   
3  Putin admits Yeltsin quit to give him a head s...   
4                             Most everywhere:  UDIs   

                                               Top17  \
0  Hunters threaten Jospin with new battle of the...   
1                          The timing of their lives   
2                                    Necaxa (Mexico)   
3         BBC worst hit as digital TV begins to bite   
4                       Most wanted:  Chloe lunettes   

                                            Top18  \
0             Kohl's successor drawn into scandal   
1                                     Dear doctor   
2                             Real Madrid (Spain)   
3                     How much can you pay for...   
4  Return of the cane 'completely off the agenda'   

                                               Top19  \
0               The difference between men and women   
1  Irish court halts IRA man's extradition to Nor...   
2                          Raja Casablanca (Morocco)   
3                                 Christmas glitches   
4                   From Sleepy Hollow to Greeneland   

                         

In [14]:
df.tail()

Date  Label                                               Top1  \
4096  2016-06-27      0  Barclays and RBS shares suspended from trading...   
4097  2016-06-28      1  2,500 Scientists To Australia: If You Want To ...   
4098  2016-06-29      1                   Explosion At Airport In Istanbul   
4099  2016-06-30      1  Jamaica proposes marijuana dispensers for tour...   
4100  2016-07-01      1  A 117-year-old woman in Mexico City finally re...   

                                                   Top2  \
4096  Pope says Church should ask forgiveness from g...   
4097  The personal details of 112,000 French police ...   
4098  Yemeni former president: Terrorism is the offs...   
4099  Stephen Hawking says pollution and 'stupidity'...   
4100   IMF chief backs Athens as permanent Olympic host   

                                                   Top3  \
4096  Poland 'shocked' by xenophobic abuse of Poles ...   
4097  S&amp;P cuts United Kingdom sovereign credit r...   
4098  UK must accept freedom of movement to access E...   
4099  Boris Johnson says he will not run for Tory pa...   
4100  The president of France says if Brexit won, so...   

                                                   Top4  \
4096  There will be no second referendum, cabinet ag...   
4097                Huge helium deposit found in Africa   
4098  Devastated: scientists too late to captive bre...   
4099  Six gay men in Ivory Coast were abused and for...   
4100  British Man Who Must Give Police 24 Hours' Not...   

                                                   Top5  \
4096      Scotland welcome to join EU, Merkel ally says   
4097  CEO of the South African state broadcaster qui...   
4098  British Labor Party leader Jeremy Corbyn loses...   
4099  Switzerland denies citizenship to Muslim immig...   
4100  100+ Nobel laureates urge Greenpeace to stop o...   

                                                   Top6  \
4096  Sterling dips below Friday's 31-year low amid ...   
4097  Brexit cost investors $2 trillion, the worst o...   
4098  A Muslim Shop in the UK Was Just Firebombed Wh...   
4099  Palestinian terrorist stabs israeli teen girl ...   
4100  Brazil: Huge spike in number of police killing...   

                                                   Top7  \
4096  No negative news about South African President...   
4097  Hong Kong democracy activists call for return ...   
4098  Mexican Authorities Sexually Torture Women in ...   
4099  Puerto Rico will default on $1 billion of debt...   
4100  Austria's highest court annuls presidential el...   

                                                   Top8  ...  \
4096  Surge in Hate Crimes in the U.K. Following U.K...  ...   
4097  Brexit: Iceland president says UK can join 'tr...  ...   
4098            UK shares and pound continue to recover  ...   
4099  Republic of Ireland fans to be awarded medal f...  ...   
4100  Facebook wins privacy case, can track any Belg...  ...   

                                                  Top16  \
4096  German lawyers to probe Erdogan over alleged w...   
4097  US, Canada and Mexico pledge 50% of power from...   
4098  Escape Tunnel, Dug by Hand, Is Found at Holoca...   
4099  Googles free wifi at Indian railway stations i...   
4100  The United States has placed Myanmar, Uzbekist...   

                                                  Top17  \
4096  Boris Johnson says the UK will continue to "in...   
4097  There is increasing evidence that Australia is...   
4098  The land under Beijing is sinking by as much a...   
4099  Mounting evidence suggests 'hobbits' were wipe...   
4100  S&amp;P revises European Union credit rating t...   

                                                  Top18  \
4096  Richard Branson is calling on the UK governmen...   
4097  Richard Branson, the founder of Virgin Group, ...   
4098  Car bomb and Anti-Islamic attack on Mosque in ...   
4099  The men who carried out Tuesday's terror attac...   
4100  India gets $1 bil

# Splitting Dataset into Train and test Datasets

In [15]:
train = df[df['Date']< '20150101']
test = df[df['Date']>'20141231']

# Text Preprocessing

In [16]:
# Removing Puntuations
data = train.iloc[:,2:27]
data.replace("[^a-zA-A]"," ", regex = True, inplace = True)

In [18]:
# Renaming column names for ease of access

list1 = [i for i in range (25)]
new_index = [str(i) for i in list1]
data.columns = new_index
data.head()

0  \
0  A  hindrance to operations   extracts from the...   
1                                           corecard   
2                   oventry caught on counter by  lo   
3                       ilgrim knows how to progress   
4                                itches and  orlocks   

                                    1  \
0                            corecard   
1                  he best lake scene   
2   nited s rivals on the road to  io   
3                  hatcher facing ban   
4       eckham off but  nited survive   

                                               2  \
0                 ughes  instant hit buoys  lues   
1                   eader   erman sleaze inquiry   
2   hatcher issues defence before trial by video   
3         c lroy calls for  rish fighting spirit   
4                         reast cancer screening   

                                               3  \
0        ack gets his skates on at ice cold Alex   
1                                   heerio  boyo   
2   olice help  mith lay down the law at  verton   
3                 eicester bin stadium blueprint   
4                                    Alan  arker   

                                             4  \
0        haos as  aracana builds up for  nited   
1                      he main recommendations   
2   ale of  rautmann bears two more retellings   
3                nited braced for  exican wave   
4       uardian readers  are you all whingers    

                                                   5  \
0   epleted  eicester prevail as  lliott spoils  ...   
1                              as  ubie killed fees    
2                                 ngland on the rack   
3  Auntie back in fashion  even if the dress look...   
4                                    ollywood  eyond   

                                                 6  \
0                  ungry  purs sense rich pickings   
1                            as  ubie killed fees    
2   akistan retaliate with call for video of  alsh   
3                     hoaib appeal goes to the top   
4                               Ashes and diamonds   

                                                   7  \
0                   unners so wide of an easy target   
1                              as  ubie killed fees    
2                ullinan continues his  ape monopoly   
3   ussain hurt by  shambles  but lays blame on e...   
4                    hingers   a formidable minority   

                                                   8  \
0       erby raise a glass to  trupar s debut double   
1   opkins  furious  at  oster s lack of  annibal...   
2              c rath puts  ndia out of their misery   
3                       ngland s decade of disasters   
4                             Alan  arker   part two   

                                          9  ...  \
0   outhgate strikes   eeds pay the penalty  ...   
1                     as  ubie killed fees   ...   
2             lair  itch bandwagon rolls on  ...   
3       evenge is sweet for jubilant  ronje  ...   
4                  huggery   oxins and  ies  ...   

                                                  15  \
0            lintoff injury piles on woe for  ngland   
1                                n the critical list   
2                         outh  elbourne  Australia    
3   utin admits  eltsin quit to give him a head s...   
4                              ost everywhere      s   

                                                  16  \
0   unters threaten  ospin with new battle of the...   
1                           he timing of their lives   
2                                     ecaxa   exico    
3             worst hit as digital    begins to bite   
4                        ost wanted    hloe lunettes   

                                               17  \
0              ohl s successor drawn into scandal   
1                                      ear doctor   
2                              eal  adrid   pain    
3    

In [21]:
# converting he headlines into Lower Case to maintain text uniformity across the dataset

for index in new_index:
    data[index] = data[index].str.lower()
data.head()


0  \
0  a  hindrance to operations   extracts from the...   
1                                           corecard   
2                   oventry caught on counter by  lo   
3                       ilgrim knows how to progress   
4                                itches and  orlocks   

                                    1  \
0                            corecard   
1                  he best lake scene   
2   nited s rivals on the road to  io   
3                  hatcher facing ban   
4       eckham off but  nited survive   

                                               2  \
0                 ughes  instant hit buoys  lues   
1                   eader   erman sleaze inquiry   
2   hatcher issues defence before trial by video   
3         c lroy calls for  rish fighting spirit   
4                         reast cancer screening   

                                               3  \
0        ack gets his skates on at ice cold alex   
1                                   heerio  boyo   
2   olice help  mith lay down the law at  verton   
3                 eicester bin stadium blueprint   
4                                    alan  arker   

                                             4  \
0        haos as  aracana builds up for  nited   
1                      he main recommendations   
2   ale of  rautmann bears two more retellings   
3                nited braced for  exican wave   
4       uardian readers  are you all whingers    

                                                   5  \
0   epleted  eicester prevail as  lliott spoils  ...   
1                              as  ubie killed fees    
2                                 ngland on the rack   
3  auntie back in fashion  even if the dress look...   
4                                    ollywood  eyond   

                                                 6  \
0                  ungry  purs sense rich pickings   
1                            as  ubie killed fees    
2   akistan retaliate with call for video of  alsh   
3                     hoaib appeal goes to the top   
4                               ashes and diamonds   

                                                   7  \
0                   unners so wide of an easy target   
1                              as  ubie killed fees    
2                ullinan continues his  ape monopoly   
3   ussain hurt by  shambles  but lays blame on e...   
4                    hingers   a formidable minority   

                                                   8  \
0       erby raise a glass to  trupar s debut double   
1   opkins  furious  at  oster s lack of  annibal...   
2              c rath puts  ndia out of their misery   
3                       ngland s decade of disasters   
4                             alan  arker   part two   

                                          9  ...  \
0   outhgate strikes   eeds pay the penalty  ...   
1                     as  ubie killed fees   ...   
2             lair  itch bandwagon rolls on  ...   
3       evenge is sweet for jubilant  ronje  ...   
4                  huggery   oxins and  ies  ...   

                                                  15  \
0            lintoff injury piles on woe for  ngland   
1                                n the critical list   
2                         outh  elbourne  australia    
3   utin admits  eltsin quit to give him a head s...   
4                              ost everywhere      s   

                                                  16  \
0   unters threaten  ospin with new battle of the...   
1                           he timing of their lives   
2                                     ecaxa   exico    
3             worst hit as digital    begins to bite   
4                        ost wanted    hloe lunettes   

                                               17  \
0              ohl s successor drawn into scandal   
1                                      ear doctor   
2                              eal  adrid   pain    
3    

In [22]:
' '.join(str(x) for x in data.iloc[1,0:25])

' corecard  he best lake scene  eader   erman sleaze inquiry  heerio  boyo  he main recommendations  as  ubie killed fees   as  ubie killed fees   as  ubie killed fees   opkins  furious  at  oster s lack of  annibal appetite  as  ubie killed fees  a tale of two tails   say what   like and   like what   say  lbows   yes and  ipples  ask force to assess risk of asteroid collision  ow   found myself at last  n the critical list  he timing of their lives  ear doctor  rish court halts   a man s extradition to  orthern  reland  urundi peace initiative fades after rebels reject  andela as mediator    points the way forward to the      ampaigners keep up pressure on  azi war crimes suspect  ane  atcliffe  et more things you wouldn t know without the movies  illennium bug fails to bite'

In [23]:
headlines = []
for row in range(0,len(data.index)):
    headlines.append(' '.join(str(x) for x in data.iloc[row,0:25]))

In [30]:
headlines[:]

['a  hindrance to operations   extracts from the leaked reports  corecard  ughes  instant hit buoys  lues  ack gets his skates on at ice cold alex  haos as  aracana builds up for  nited  epleted  eicester prevail as  lliott spoils  verton s party  ungry  purs sense rich pickings  unners so wide of an easy target  erby raise a glass to  trupar s debut double  outhgate strikes   eeds pay the penalty  ammers hand  obson a youthful lesson  aints party like it s       ear wolves have turned into lambs  tump mike catches testy  ough s taunt  anger escapes to hit      lintoff injury piles on woe for  ngland  unters threaten  ospin with new battle of the  omme  ohl s successor drawn into scandal  he difference between men and women  ara  enver  nurse turned solicitor  iana s landmine crusade put  ories in a panic  eltsin s resignation caught opposition flat footed  ussian roulette  old out  ecovering a title',
 ' corecard  he best lake scene  eader   erman sleaze inquiry  heerio  boyo  he main

# Conversion of sentences into Vectors of the Train dataset for Implementing Machine learning Algorithms

In [31]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.ensemble import RandomForestClassifier

In [32]:
# implementation of BOW (Bag of Words vectoriser)

countvector = CountVectorizer(ngram_range = (2,2))
traindataset = countvector.fit_transform(headlines)

In [39]:
traindataset[:]

<3975x605642 sparse matrix of type '<class 'numpy.int64'>'
	with 1051731 stored elements in Compressed Sparse Row format>

# Fitting Random Forest Classifer on the Train dataset

In [63]:
randomclassifier  = RandomForestClassifier(n_estimators = 200, criterion = 'entropy')
randomclassifier.fit(traindataset, train['Label'])


RandomForestClassifier(criterion='entropy', n_estimators=200)

# Joining each column of a row into a sentence of test dataset;   combining all the sentences of all the rows; implementing BOW vectoriser on test dataset with removing puntuations

In [64]:
# joining each column of a row into a sentence of test dataset 
# combine all the sentences of all the rows
# implement BOW vectoriser on test dataset
# predict test data using randomforest classifier

test_transform = []
for row in range(0,len(test.index)):
    test_transform.append(' '.join(str(x) for x in test.iloc[row,2:27]))
test_dataset = countvector.transform(test_transform)


# predicting stock sentiments on test data using randomforest classifier

In [65]:
predictions = randomclassifier.predict(test_dataset)

In [66]:
predictions

array([1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1,
       1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1,

# Checking model accuracy and prediction accuracy with the help of lassification  report, confusion matrix and accuracy score

In [67]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score


In [68]:
matrix = confusion_matrix(test['Label'], predictions)
print(matrix)
score = accuracy_score(test['Label'],predictions)
print(score)
report = classification_report(test['Label'],predictions)
print(report)

[[132  54]
 [ 29 163]]
0.7804232804232805
              precision    recall  f1-score   support

           0       0.82      0.71      0.76       186
           1       0.75      0.85      0.80       192

    accuracy                           0.78       378
   macro avg       0.79      0.78      0.78       378
weighted avg       0.78      0.78      0.78       378



# Feature Extraction Using TFIDF to improve Model Accuracy

In [59]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.ensemble import RandomForestClassifier

In [61]:
# implementation of TFIDF

tfidfvector = TfidfVectorizer(ngram_range = (2,2))
traindataset = tfidfvector.fit_transform(headlines)

In [62]:
randomclassifier  = RandomForestClassifier(n_estimators = 200, criterion = 'entropy')
randomclassifier.fit(traindataset, train['Label'])

RandomForestClassifier(criterion='entropy', n_estimators=200)

In [70]:
# joining each column of a row into a sentence of test dataset 
# combine all the sentences of all the rows
# implement BOW vectoriser on test dataset
# predict test data using randomforest classifier

test_transform = []
for row in range(0,len(test.index)):
    test_transform.append(' '.join(str(x) for x in test.iloc[row,2:27]))
test_dataset = tfidfvector.transform(test_transform)

In [71]:
predictions = randomclassifier.predict(test_dataset)

In [72]:
predictions

array([1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1,
       1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1,
       1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,

In [73]:
matrix = confusion_matrix(test['Label'], predictions)
print(matrix)
score = accuracy_score(test['Label'],predictions)
print(score)
report = classification_report(test['Label'],predictions)
print(report)

[[135  51]
 [ 24 168]]
0.8015873015873016
              precision    recall  f1-score   support

           0       0.85      0.73      0.78       186
           1       0.77      0.88      0.82       192

    accuracy                           0.80       378
   macro avg       0.81      0.80      0.80       378
weighted avg       0.81      0.80      0.80       378



# Deploying Naive Bayes Algorithm to get more accurate predictions

In [77]:
from sklearn.naive_bayes import MultinomialNB

In [78]:
naive = MultinomialNB()
naive.fit(traindataset, train['Label'])

MultinomialNB()

In [79]:
test_transform = []
for row in range(0,len(test.index)):
    test_transform.append(' '.join(str(x) for x in test.iloc[row,2:27]))
test_dataset = tfidfvector.transform(test_transform)
predictions = naive.predict(test_dataset)
predictions

array([1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1,
       1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1,
       0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [80]:
matrix = confusion_matrix(test['Label'], predictions)
print(matrix)
score = accuracy_score(test['Label'],predictions)
print(score)
report = classification_report(test['Label'],predictions)
print(report)

[[130  56]
 [  0 192]]
0.8518518518518519
              precision    recall  f1-score   support

           0       1.00      0.70      0.82       186
           1       0.77      1.00      0.87       192

    accuracy                           0.85       378
   macro avg       0.89      0.85      0.85       378
weighted avg       0.89      0.85      0.85       378

